version: '3.8'

services:
  frontend-app:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "4173:4173"
      - "5174:5174"
      - "3000:3000"
    volumes:
      - ./app:/app

